name = "play"
main = "worker.js"
compatibility_date = "2024-10-01"

[[kv_namespaces]]
binding = "GOLF"
id = ""         # will fill in after we create the KV namespace
preview_id = "" # will fill in after we create the KV namespace
